### ISSUE TITLE
Package Version Update

### ISSUE THREAD

**Issue by PH-Lazurous** [kristofferh/passwordless-sequelize#1]
I know this hasn't been updated in a while but the latest versions worked fine in my lab by simply updating the package.json. The current versions failed to compile on my Win X64 machine (admittedly I gave up quickly on troubleshooting) but I simply forked your project and tested with latest versions without issue. Thought I would share for those who ran into it as well. 

`"dependencies": {
    "bcrypt": "^4.0.1",
    "sequelize": "^5.21.5"
  },`

**Comment by PH-Lazurous** [comment]
https://github.com/kristofferh/passwordless-sequelize/pull/2

**Comment by kristofferh** [comment]
Fixed with #2
